-- kudos feature: hashtags, kudos, kudo_hashtags, kudo_images
-- Storage bucket kudo-images + RLS policies
-- RPC create_kudo() — atomic insert (kudos + kudo_hashtags + kudo_images)

-- ============================================================
-- Tables
-- ============================================================

create table if not exists public.hashtags (
  id         uuid        primary key default gen_random_uuid(),
  name       text        not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.kudos (
  id             uuid        primary key,
  sender_id      uuid        not null references public.profiles (id) on delete restrict,
  receiver_id    uuid        not null references public.profiles (id) on delete restrict,
  content_html   text        not null,
  is_anonymous   boolean     not null default false,
  anonymous_name text,
  created_at     timestamptz not null default now(),
  constraint kudos_sender_neq_receiver check (sender_id <> receiver_id)
);

create index if not exists kudos_receiver_id_idx on public.kudos (receiver_id);
create index if not exists kudos_created_at_idx  on public.kudos (created_at desc);

create table if not exists public.kudo_hashtags (
  kudo_id    uuid not null references public.kudos (id) on delete cascade,
  hashtag_id uuid not null references public.hashtags (id),
  primary key (kudo_id, hashtag_id)
);

create table if not exists public.kudo_images (
  id           uuid        primary key default gen_random_uuid(),
  kudo_id      uuid        not null references public.kudos (id) on delete cascade,
  storage_path text        not null,
  sort_order   integer     not null default 0,
  created_at   timestamptz not null default now()
);

-- ============================================================
-- Row Level Security
-- ============================================================

alter table public.hashtags     enable row level security;
alter table public.kudos        enable row level security;
alter table public.kudo_hashtags enable row level security;
alter table public.kudo_images  enable row level security;

-- hashtags: authenticated can SELECT only
create policy "hashtags_select_authenticated"
  on public.hashtags
  for select
  to authenticated
  using (true);

-- kudos: INSERT only own row; SELECT for all authenticated
create policy "kudos_insert_own"
  on public.kudos
  for insert
  to authenticated
  with check (auth.uid() = sender_id);

create policy "kudos_select_authenticated"
  on public.kudos
  for select
  to authenticated
  using (true);

-- kudo_hashtags: INSERT via owned kudo; SELECT for authenticated
create policy "kudo_hashtags_insert_via_owned_kudo"
  on public.kudo_hashtags
  for insert
  to authenticated
  with check (
    exists (
      select 1 from public.kudos k
      where k.id = kudo_id and k.sender_id = auth.uid()
    )
  );

create policy "kudo_hashtags_select_authenticated"
  on public.kudo_hashtags
  for select
  to authenticated
  using (true);

-- kudo_images: INSERT via owned kudo; SELECT for authenticated
create policy "kudo_images_insert_via_owned_kudo"
  on public.kudo_images
  for insert
  to authenticated
  with check (
    exists (
      select 1 from public.kudos k
      where k.id = kudo_id and k.sender_id = auth.uid()
    )
  );

create policy "kudo_images_select_authenticated"
  on public.kudo_images
  for select
  to authenticated
  using (true);

-- ============================================================
-- Storage bucket: kudo-images (private)
-- ============================================================

insert into storage.buckets (id, name, public)
values ('kudo-images', 'kudo-images', false)
on conflict (id) do nothing;

-- Authenticated users: INSERT into their own folder {uid}/...
create policy "kudo_images_storage_insert"
  on storage.objects
  for insert
  to authenticated
  with check (
    bucket_id = 'kudo-images'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

-- Authenticated users: SELECT any kudo image
create policy "kudo_images_storage_select"
  on storage.objects
  for select
  to authenticated
  using (bucket_id = 'kudo-images');

-- Authenticated users: DELETE their own uploads (own folder {uid}/...)
create policy "kudo_images_storage_delete"
  on storage.objects
  for delete
  to authenticated
  using (
    bucket_id = 'kudo-images'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

-- ============================================================
-- RPC: create_kudo() — atomic (security invoker)
-- ============================================================
-- p_kudo_id    : uuid generated by the client (also used as image upload path prefix)
-- p_receiver_id: uuid of the recipient profile
-- p_content_html: sanitized HTML (server sanitizes before calling)
-- p_is_anonymous: whether to hide sender identity from receiver
-- p_anonymous_name: optional alias shown instead of real name
-- p_hashtag_ids: array of 1-5 existing hashtag UUIDs
-- p_image_paths : array of 0-5 Storage paths already uploaded

create or replace function public.create_kudo(
  p_kudo_id       uuid,
  p_receiver_id   uuid,
  p_content_html  text,
  p_is_anonymous  boolean,
  p_anonymous_name text,
  p_hashtag_ids   uuid[],
  p_image_paths   text[]
)
returns uuid
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_sender_id  uuid;
  v_tag_count  int;
  v_img_count  int;
  i            int;
begin
  -- 1. Resolve caller identity
  v_sender_id := auth.uid();
  if v_sender_id is null then
    raise exception 'Not authenticated' using errcode = 'P0001';
  end if;

  -- 2. Validate: receiver must differ from sender
  if p_receiver_id = v_sender_id then
    raise exception 'Sender and receiver must differ' using errcode = 'P0002';
  end if;

  -- 3. Validate: hashtag_ids 1–5
  v_tag_count := coalesce(array_length(p_hashtag_ids, 1), 0);
  if v_tag_count < 1 or v_tag_count > 5 then
    raise exception 'hashtag_ids must have 1–5 elements, got %', v_tag_count using errcode = 'P0003';
  end if;

  -- 4. Validate: all hashtag UUIDs exist
  if exists (
    select 1
    from unnest(p_hashtag_ids) as t(id)
    where not exists (select 1 from public.hashtags h where h.id = t.id)
  ) then
    raise exception 'One or more hashtag_ids do not exist' using errcode = 'P0004';
  end if;

  -- 5. Validate: image_paths 0–5
  v_img_count := coalesce(array_length(p_image_paths, 1), 0);
  if v_img_count > 5 then
    raise exception 'image_paths must have at most 5 elements, got %', v_img_count using errcode = 'P0005';
  end if;

  -- 5b. Validate: every image path must be under the caller's uid folder
  if v_img_count > 0 then
    if exists (
      select 1 from unnest(p_image_paths) as t(path)
      where split_part(t.path, '/', 1) <> v_sender_id::text
    ) then
      raise exception 'image paths must be under caller uid folder' using errcode = 'P0006';
    end if;
  end if;

  -- 6. Insert kudo
  insert into public.kudos (id, sender_id, receiver_id, content_html, is_anonymous, anonymous_name)
  values (p_kudo_id, v_sender_id, p_receiver_id, p_content_html, p_is_anonymous, p_anonymous_name);

  -- 7. Insert kudo_hashtags
  insert into public.kudo_hashtags (kudo_id, hashtag_id)
  select p_kudo_id, unnest(p_hashtag_ids);

  -- 8. Insert kudo_images (with sort_order by position)
  for i in 1 .. v_img_count loop
    insert into public.kudo_images (kudo_id, storage_path, sort_order)
    values (p_kudo_id, p_image_paths[i], i - 1);
  end loop;

  return p_kudo_id;
end;
$$;
